url: "https://jcmcginnis.com"
timezone: America/Toronto
permalink: pretty

# Social links for JSON-LD structured data (used by bridgetown-seo-tag)
social:
  name: Jesse McGinnis
  links:
    - https://twitter.com/elsom25
    - https://github.com/elsom25
    - https://www.linkedin.com/in/jcmcginnis
    - https://www.facebook.com/jcmcginnis

pagination:
  enabled: true

collections:
  posts:
    output: true
    permalink: /blog/:title/
  # talks collection is defined in config/initializers.rb (Ruby DSL preferred in Bridgetown 2.0)

defaults:
  - scope:
      collection: posts
    values:
      layout: post
  - scope:
      collection: talks
    values:
      layout: talk

template_engine: erb

# Exclude Tailwind source from static file copying (it gets compiled to output/)
exclude:
  - assets/css/tailwind.css
