url: "https://jcmcginnis.com"
timezone: America/Toronto
permalink: pretty

# Social links for JSON-LD structured data (used by bridgetown-seo-tag)
social:
  name: Jesse McGinnis
  links:
    - https://twitter.com/elsom25
    - https://github.com/elsom25
    - https://www.linkedin.com/in/jcmcginnis
    - https://www.facebook.com/jcmcginnis

pagination:
  enabled: true

defaults:
  - scope:
      collection: posts
    values:
      layout: post
      page_id: post
  - scope:
      collection: talks
    values:
      layout: talk
      page_id: talk

template_engine: erb
