min_version = "2025.4.12"

[tools]
node = "24.11.1"
sops = "latest"
age = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[env]
_.file = [
  ".env.development",
  ".env.secret.json",
  ".env.local",
]
